bank_market_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_DB_HOST') }}"
      port: "{{ env_var('DBT_DB_PORT') | int }}"
      user: "{{ env_var('DBT_DB_USER') }}"
      pass: "{{ env_var('DBT_DB_PASSWORD') }}"
      dbname: "{{ env_var('DBT_DB_NAME') }}"
      schema: "{{ env_var('DBT_DB_SCHEMA', 'analytics') }}"
      threads: "{{ env_var('DBT_THREADS', '4') | int }}"
    olap:
      type: clickhouse
      host: "{{ env_var('DBT_CH_HOST') }}"
      port: "{{ env_var('DBT_CH_HTTP_PORT') | int }}"
      user: "{{ env_var('DBT_CH_USER') }}"
      password: "{{ env_var('DBT_CH_PASSWORD', '') }}"
      schema: "{{ env_var('DBT_CH_DATABASE', 'olap') }}"
      threads: "{{ env_var('DBT_THREADS', '4') | int }}"
